import requests
youurls = "https://playground.learnqa.ru/ajax/api/compare_query_type"

print("************     1    ************")
resp=requests.get(youurls)
print(resp.status_code, resp.text)
resp=requests.post(youurls)
print(resp.status_code, resp.text)
resp=requests.put(youurls)
print(resp.status_code, resp.text)
resp=requests.delete(youurls)
print(resp.status_code, resp.text)

print("************     2    ************")
resp=requests.head(youurls)
print(resp.status_code, resp.text)
resp=requests.head(youurls, data={"method":"HEAD"})
print(resp.status_code, resp.text)
resp=requests.patch(youurls)
print(resp.status_code, resp.text)
resp=requests.patch(youurls, data={"method":"PATCH"})
print(resp.status_code, resp.text)
resp=requests.options(youurls)
print(resp.status_code, resp.text)
resp=requests.patch(youurls, data={"method":"OPTIONS"})
print(resp.status_code, resp.text)

print("************     3    ************")
resp=requests.get(youurls, params={"method":"GET"})
print(resp.status_code, resp.text)
resp=requests.post(youurls, data={"method":"POST"})
print(resp.status_code, resp.text)
resp=requests.put(youurls, data={"method":"PUT"})
print(resp.status_code, resp.text)
resp=requests.delete(youurls, data={"method": "DELETE"})
print(resp.status_code, resp.text)

print("************     4    ************")
mtype=("GET", "POST", "PUT", "DELETE", "HEAD", "PATCH", "OPTIONS")
for i in mtype:
    resp1=requests.get(youurls,params={"method": i},)
    print(f"Параметр {i} запрос GET", resp1.status_code, resp1.text)
    resp1=requests.post(youurls,data={"method": i})
    print(f"Параметр {i} запрос POST", resp1.status_code, resp1.text)
    resp1=requests.put(youurls,data={"method": i})
    print(f"Параметр {i} запрос PUT", resp1.status_code, resp1.text)
    resp1=requests.delete(youurls,data={"method": i})
    print(f"Параметр {i} запрос DELETE", resp1.status_code, resp1.text)
    #
    resp1=requests.head(youurls,data={"method": i})
    print(f"Параметр {i} запрос head", resp1.status_code, resp1.text)
    resp1=requests.patch(youurls,data={"method": i})
    print(f"Параметр {i} запрос patch", resp1.status_code, resp1.text)
    resp1=requests.options(youurls,data={"method": i})
    print(f"Параметр {i} запрос options", resp1.status_code, resp1.text)
    print("-")